CREATE TABLE `recruitmentApplications` (
	`id` int AUTO_INCREMENT NOT NULL,
	`discordUsername` varchar(255) NOT NULL,
	`htbProfile` text,
	`thmProfile` text,
	`hcProfile` text,
	`githubProfile` text,
	`blogUrl` text,
	`motivation` text NOT NULL,
	`mainSpecialty` varchar(255) NOT NULL,
	`yearsOfExperience` varchar(50) NOT NULL,
	`biggestChallenge` text,
	`categoriesToImprove` varchar(500),
	`weeklyCommitment` varchar(50) NOT NULL,
	`idealTeamDynamic` text,
	`automatedScore` int NOT NULL DEFAULT 0,
	`status` enum('pending','reviewed','accepted','rejected') NOT NULL DEFAULT 'pending',
	`reviewNotes` text,
	`feedbackMessage` text,
	`reviewedAt` timestamp,
	`decidedAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `recruitmentApplications_id` PRIMARY KEY(`id`)
);
